import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Loader from "../components/Loader";
import { useApi } from "../hooks/useApi";
import { useToast } from "../hooks/useToast";

const formatKes = (value) =>
  new Intl.NumberFormat("en-KE", {
    style: "currency",
    currency: "KES",
    maximumFractionDigits: 0,
  }).format(Number(value || 0));

const formatPercent = (value) => {
  if (value === null || value === undefined || Number.isNaN(Number(value))) {
    return "n/a";
  }
  return `${(Number(value) * 100).toFixed(1)}%`;
};

function LineItems({ items, emptyLabel = "No line items available yet." }) {
  if (!items?.length) {
    return <p className="lead">{emptyLabel}</p>;
  }

  return (
    <div className="doc-list">
      {items.map((item) => (
        <div key={`${item.code || item.partner || item.name}-${item.amount}`} className="doc-row">
          <div>
            <strong>{item.name || item.partner}</strong>
            {item.code ? <p>{item.code}</p> : null}
          </div>
          <div>
            <strong>{formatKes(item.amount)}</strong>
          </div>
        </div>
      ))}
    </div>
  );
}

function SummaryRows({ rows }) {
  return (
    <div className="stack">
      {rows.map((row) => (
        <div key={row.label} className={`summary-line${row.total ? " statement-total" : ""}`}>
          <strong>{row.label}</strong>
          <span>{row.value}</span>
        </div>
      ))}
    </div>
  );
}

export default function Reports() {
  const { finance, ai } = useApi();
  const toast = useToast();
  const [statements, setStatements] = useState(null);
  const [aiData, setAiData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const [statementPayload, aiPayload] = await Promise.all([
        finance.getFinancialStatements(),
        ai.getAICFO(),
      ]);
      setStatements(statementPayload);
      setAiData(aiPayload);
    } catch (err) {
      setError(err.message || "Failed to load reports.");
      toast.error("Reports unavailable", err.message || "We could not load the reporting workspace.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const healthCards = useMemo(() => {
    const health = statements?.health || {};
    return [
      {
        label: "Gross margin",
        value: formatPercent(health.gross_margin_pct),
        hint: "Gross profit as a share of revenue",
      },
      {
        label: "Net margin",
        value: formatPercent(health.net_margin_pct),
        hint: "Profit after expenses and appropriations",
      },
      {
        label: "Current ratio",
        value: health.current_ratio ? `${Number(health.current_ratio).toFixed(2)}x` : "n/a",
        hint: "Current assets divided by current liabilities",
      },
      {
        label: "Working capital",
        value: formatKes(health.working_capital || 0),
        hint: "Short-term liquidity cushion",
      },
      {
        label: "Debt ratio",
        value: formatPercent(health.debt_ratio),
        hint: "Share of assets funded by liabilities",
      },
      {
        label: "Operating cash flow",
        value: formatKes(health.operating_cash_flow || 0),
        hint: "Net cash generated by operations",
      },
    ];
  }, [statements]);

  if (loading) {
    return <Loader label="Loading reports..." />;
  }

  const profitOrLoss = statements?.profit_or_loss || {};
  const financialPosition = statements?.financial_position || {};
  const cashFlow = statements?.cash_flow || {};
  const manufacturing = statements?.special_reports?.manufacturing_account;
  const appropriation = statements?.special_reports?.partnership_appropriation;

  return (
    <section className="page-shell">
      <header className="hero-banner">
        <div>
          <span className="eyebrow">Reporting Workspace</span>
          <h2>Read the business clearly, then act on the next 90 days.</h2>
          <p className="lead">
            Detailed statements, health ratios, and business-type-specific reports now sit in one
            place instead of hiding behind summary cards.
          </p>
        </div>
        <div className="hero-actions">
          <Link className="ghost-button ghost-button--light" to="/app">
            Back To Dashboard
          </Link>
          <button type="button" className="ghost-button ghost-button--light" onClick={load}>
            Refresh
          </button>
        </div>
      </header>

      {error ? <div className="form-error">{error}</div> : null}

      <div className="metric-grid">
        {healthCards.map((item) => (
          <article key={item.label} className="metric-card">
            <span className="metric-label">{item.label}</span>
            <strong className="metric-value">{item.value}</strong>
            <span className="metric-helper">{item.hint}</span>
          </article>
        ))}
      </div>

      <div className="dashboard-grid">
        <section className="panel stack">
          <div className="panel-header">
            <div>
              <span className="eyebrow">Statement Of Profit Or Loss</span>
              <h3>Detailed performance</h3>
            </div>
          </div>

          <SummaryRows
            rows={[
              { label: "Revenue", value: formatKes(profitOrLoss?.revenue?.total || 0) },
              { label: "Cost of sales", value: formatKes(profitOrLoss?.cost_of_sales?.total || 0) },
              { label: "Gross profit", value: formatKes(profitOrLoss?.gross_profit || 0), total: true },
              {
                label: "Operating expenses",
                value: formatKes(profitOrLoss?.operating_expenses?.total || 0),
              },
              { label: "Other expenses", value: formatKes(profitOrLoss?.other_expenses?.total || 0) },
              { label: "Tax expense", value: formatKes(profitOrLoss?.tax_expense?.total || 0) },
              {
                label: "Appropriations",
                value: formatKes(profitOrLoss?.appropriations?.total || 0),
              },
              {
                label: "Profit for the period",
                value: formatKes(profitOrLoss?.current_period_result || 0),
                total: true,
              },
            ]}
          />

          <div className="report-grid">
            <div className="stack">
              <strong>Revenue lines</strong>
              <LineItems
                items={profitOrLoss?.revenue?.items}
                emptyLabel="No revenue accounts have activity yet."
              />
            </div>

            <div className="stack">
              <strong>Expense lines</strong>
              <LineItems
                items={[
                  ...(profitOrLoss?.cost_of_sales?.items || []),
                  ...(profitOrLoss?.operating_expenses?.items || []),
                  ...(profitOrLoss?.other_expenses?.items || []),
                  ...(profitOrLoss?.tax_expense?.items || []),
                  ...(profitOrLoss?.appropriations?.items || []),
                ]}
                emptyLabel="No expense accounts have activity yet."
              />
            </div>
          </div>
        </section>

        <section className="panel stack">
          <div className="panel-header">
            <div>
              <span className="eyebrow">Statement Of Financial Position</span>
              <h3>Detailed balance sheet</h3>
            </div>
            <span
              className={`status-pill ${
                financialPosition?.balanced ? "status-pill--ready" : "status-pill--warning"
              }`}
            >
              {financialPosition?.balanced ? "Balanced" : "Needs review"}
            </span>
          </div>

          <SummaryRows
            rows={[
              { label: "Current assets", value: formatKes(financialPosition?.current_assets?.total || 0) },
              { label: "Non-current assets", value: formatKes(financialPosition?.non_current_assets?.total || 0) },
              { label: "Total assets", value: formatKes(financialPosition?.total_assets || 0), total: true },
              {
                label: "Current liabilities",
                value: formatKes(financialPosition?.current_liabilities?.total || 0),
              },
              {
                label: "Non-current liabilities",
                value: formatKes(financialPosition?.non_current_liabilities?.total || 0),
              },
              { label: "Total liabilities", value: formatKes(financialPosition?.total_liabilities || 0) },
              {
                label: "Current year earnings",
                value: formatKes(financialPosition?.equity?.current_year_earnings || 0),
              },
              { label: "Total equity", value: formatKes(financialPosition?.equity?.total || 0), total: true },
            ]}
          />

          <div className="report-grid">
            <div className="stack">
              <strong>Assets</strong>
              <LineItems
                items={[
                  ...(financialPosition?.current_assets?.items || []),
                  ...(financialPosition?.non_current_assets?.items || []),
                ]}
                emptyLabel="No asset balances available yet."
              />
            </div>
            <div className="stack">
              <strong>Liabilities and equity</strong>
              <LineItems
                items={[
                  ...(financialPosition?.current_liabilities?.items || []),
                  ...(financialPosition?.non_current_liabilities?.items || []),
                  ...(financialPosition?.equity?.items || []),
                ]}
                emptyLabel="No liability or equity balances available yet."
              />
            </div>
          </div>
        </section>
      </div>

      <div className="dashboard-grid">
        <section className="panel stack">
          <div className="panel-header">
            <div>
              <span className="eyebrow">Statement Of Cash Flows</span>
              <h3>Where cash moved</h3>
            </div>
          </div>

          <SummaryRows
            rows={[
              { label: "Opening cash", value: formatKes(cashFlow?.opening_cash || 0) },
              { label: "Operating cash flow", value: formatKes(cashFlow?.operating?.total || 0) },
              { label: "Investing cash flow", value: formatKes(cashFlow?.investing?.total || 0) },
              { label: "Financing cash flow", value: formatKes(cashFlow?.financing?.total || 0) },
              { label: "Net change in cash", value: formatKes(cashFlow?.net_change_in_cash || 0) },
              { label: "Ending cash", value: formatKes(cashFlow?.ending_cash || 0), total: true },
            ]}
          />

          <div className="report-grid">
            <div className="stack">
              <strong>Operating activity</strong>
              <LineItems
                items={(cashFlow?.operating?.items || []).map((item) => ({
                  name: `${item.memo || item.entry_number}`,
                  code: item.entry_date,
                  amount: item.amount,
                }))}
                emptyLabel="No operating cash movement yet."
              />
            </div>
            <div className="stack">
              <strong>Investing and financing</strong>
              <LineItems
                items={[
                  ...(cashFlow?.investing?.items || []).map((item) => ({
                    name: `${item.memo || item.entry_number}`,
                    code: `${item.entry_date} · Investing`,
                    amount: item.amount,
                  })),
                  ...(cashFlow?.financing?.items || []).map((item) => ({
                    name: `${item.memo || item.entry_number}`,
                    code: `${item.entry_date} · Financing`,
                    amount: item.amount,
                  })),
                ]}
                emptyLabel="No investing or financing cash movement yet."
              />
            </div>
          </div>
        </section>

        <section className="panel stack">
          <div className="panel-header">
            <div>
              <span className="eyebrow">Forecast And Actions</span>
              <h3>What happens next</h3>
            </div>
          </div>

          <div className="forecast-stack">
            {(aiData?.forecast || []).map((item) => (
              <div key={item.label} className="forecast-row">
                <div>
                  <strong>{item.label}</strong>
                  <p className="subtle-text">Projected cash balance</p>
                </div>
                <strong>{formatKes(item.projected_cash)}</strong>
              </div>
            ))}
          </div>

          <div className="insight-card insight-card--answer">
            <strong>AI CFO narrative</strong>
            <p>{aiData?.summary || "AI CFO will narrate the next move when enough data is available."}</p>
          </div>

          {(aiData?.top_actions || []).length ? (
            <div className="stack">
              {aiData.top_actions.map((action) => (
                <div key={action} className="alert-card alert-card--positive">
                  <strong>Recommended action</strong>
                  <span>{action}</span>
                </div>
              ))}
            </div>
          ) : null}
        </section>
      </div>

      {manufacturing ? (
        <section className="panel stack">
          <div className="panel-header">
            <div>
              <span className="eyebrow">Manufacturing Account</span>
              <h3>Production cost movement</h3>
            </div>
          </div>

          <SummaryRows
            rows={[
              { label: "Raw materials purchases", value: formatKes(manufacturing.raw_materials_purchases) },
              { label: "Raw materials issued", value: formatKes(manufacturing.raw_materials_issued) },
              { label: "Direct labor", value: formatKes(manufacturing.direct_labor) },
              { label: "Factory overheads", value: formatKes(manufacturing.factory_overheads) },
              { label: "Prime cost", value: formatKes(manufacturing.prime_cost), total: true },
              {
                label: "Manufacturing cost added",
                value: formatKes(manufacturing.manufacturing_cost_added),
              },
              {
                label: "Cost transferred to finished goods",
                value: formatKes(manufacturing.cost_of_production_transferred),
                total: true,
              },
              { label: "Closing raw materials", value: formatKes(manufacturing.closing_raw_materials) },
              { label: "Closing work in progress", value: formatKes(manufacturing.closing_work_in_progress) },
              { label: "Closing finished goods", value: formatKes(manufacturing.closing_finished_goods) },
            ]}
          />
        </section>
      ) : null}

      {appropriation ? (
        <section className="panel stack">
          <div className="panel-header">
            <div>
              <span className="eyebrow">Appropriation Account</span>
              <h3>Partnership profit sharing</h3>
            </div>
          </div>

          <SummaryRows
            rows={[
              {
                label: "Profit before appropriation",
                value: formatKes(appropriation.profit_before_appropriation),
              },
              {
                label: "Interest on drawings",
                value: formatKes(appropriation.interest_on_drawings?.total || 0),
              },
              {
                label: "Adjusted profit available",
                value: formatKes(appropriation.adjusted_profit_available),
                total: true,
              },
              {
                label: "Interest on capital",
                value: formatKes(appropriation.interest_on_capital?.total || 0),
              },
              {
                label: "Partner salaries",
                value: formatKes(appropriation.partner_salaries?.total || 0),
              },
              {
                label: "Residual profit",
                value: formatKes(appropriation.residual_profit),
              },
              {
                label: "Profit share allocations",
                value: formatKes(appropriation.profit_share_allocations?.total || 0),
                total: true,
              },
            ]}
          />

          <div className="report-grid">
            <div className="stack">
              <strong>Partner charges and allowances</strong>
              <LineItems
                items={[
                  ...(appropriation.interest_on_drawings?.items || []).map((item) => ({
                    ...item,
                    name: `${item.partner} · interest on drawings`,
                  })),
                  ...(appropriation.interest_on_capital?.items || []).map((item) => ({
                    ...item,
                    name: `${item.partner} · interest on capital`,
                  })),
                  ...(appropriation.partner_salaries?.items || []).map((item) => ({
                    ...item,
                    name: `${item.partner} · salary`,
                  })),
                ]}
                emptyLabel="No partner-specific appropriation lines yet."
              />
            </div>
            <div className="stack">
              <strong>Profit allocations</strong>
              <LineItems
                items={appropriation.profit_share_allocations?.items || []}
                emptyLabel="No partner profit allocations posted yet."
              />
            </div>
          </div>
        </section>
      ) : null}
    </section>
  );
}
